# ==========================================
# Server 基础配置
# ==========================================
server:
  name: "go-micro-template"
  mode: "debug"
  port: 58080            # 服务监听端口
  version: "v1.0.0"
  register_ip: "192.168.31.29" # 你的本机局域网 IP (用于注册到 Consul)

  # ==========================================
  # Consul 注册中心 (关键修复：必须顶格写！)
  # ==========================================
  consul:
    host: "127.0.0.1"      # Consul 本地地址
    port: 8500             # Consul 端口

# ==========================================
# JWT 配置 (注意：必须顶格写，不要缩进到 server 里)
# ==========================================
jwt:
  signing_key: "web3-is-future"
  expire: 86400



# ==========================================
# MySQL 数据库
# ==========================================
mysql:
  host: "127.0.0.1"
  port: 3306
  name: "micro_db"       # 数据库名称
  user: "root"
  password: "123456"     # 你的数据库密码
  max_idle: 10
  max_open: 100

# ==========================================
# Redis 缓存
# ==========================================
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

# ==========================================
# Web3 区块链节点配置
# ==========================================
chains:
  # 1. 以太坊主网 (Infura)
  - chain_name: "ethereum_mainnet"
    chain_id: 1
    rpc_url: "https://mainnet.infura.io/v3/Your_Key"
    wss_url: ""
  
  # 2. 币安智能链 (BSC)
  - chain_name: "bsc_mainnet"
    chain_id: 56
    rpc_url: "https://bsc-dataseed.binance.org"
    wss_url: ""